// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Medium struct {
	ID                  int64          `json:"id"`
	ThreadID            string         `json:"thread_id"`
	Board               string         `json:"board"`
	PostNo              int64          `json:"post_no"`
	Filename            string         `json:"filename"`
	OriginalFilename    sql.NullString `json:"original_filename"`
	FileExt             sql.NullString `json:"file_ext"`
	FileSize            sql.NullInt64  `json:"file_size"`
	Width               sql.NullInt64  `json:"width"`
	Height              sql.NullInt64  `json:"height"`
	Md5Hash             sql.NullString `json:"md5_hash"`
	MediaType           sql.NullString `json:"media_type"`
	SourceUrl           sql.NullString `json:"source_url"`
	ThumbnailUrl        sql.NullString `json:"thumbnail_url"`
	LocalPath           sql.NullString `json:"local_path"`
	DownloadStatus      sql.NullString `json:"download_status"`
	DownloadAttempts    sql.NullInt64  `json:"download_attempts"`
	LastDownloadAttempt sql.NullTime   `json:"last_download_attempt"`
	CreatedAt           time.Time      `json:"created_at"`
}

type Post struct {
	ID                int64          `json:"id"`
	ThreadID          string         `json:"thread_id"`
	Board             string         `json:"board"`
	PostNo            int64          `json:"post_no"`
	Timestamp         int64          `json:"timestamp"`
	Name              string         `json:"name"`
	Tripcode          sql.NullString `json:"tripcode"`
	UserID            sql.NullString `json:"user_id"`
	Country           sql.NullString `json:"country"`
	CountryName       sql.NullString `json:"country_name"`
	Flag              sql.NullString `json:"flag"`
	FlagName          sql.NullString `json:"flag_name"`
	Subject           sql.NullString `json:"subject"`
	Comment           sql.NullString `json:"comment"`
	CleanText         sql.NullString `json:"clean_text"`
	ContentHash       sql.NullString `json:"content_hash"`
	Source            string         `json:"source"`
	ParsingStatus     string         `json:"parsing_status"`
	Filename          sql.NullString `json:"filename"`
	FileExt           sql.NullString `json:"file_ext"`
	FileSize          sql.NullInt64  `json:"file_size"`
	ImageWidth        sql.NullInt64  `json:"image_width"`
	ImageHeight       sql.NullInt64  `json:"image_height"`
	ThumbnailWidth    sql.NullInt64  `json:"thumbnail_width"`
	ThumbnailHeight   sql.NullInt64  `json:"thumbnail_height"`
	Md5Hash           sql.NullString `json:"md5_hash"`
	IsOp              sql.NullBool   `json:"is_op"`
	HasMediaProcessed sql.NullBool   `json:"has_media_processed"`
	CreatedAt         time.Time      `json:"created_at"`
}

type Quote struct {
	ID               int64          `json:"id"`
	ThreadID         string         `json:"thread_id"`
	Board            string         `json:"board"`
	PostNo           int64          `json:"post_no"`
	QuoteText        string         `json:"quote_text"`
	QuoteType        string         `json:"quote_type"`
	ReferencedPostNo sql.NullInt64  `json:"referenced_post_no"`
	QuoteContext     sql.NullString `json:"quote_context"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Reply struct {
	ID        int64          `json:"id"`
	ThreadID  string         `json:"thread_id"`
	Board     string         `json:"board"`
	FromPost  int64          `json:"from_post"`
	ToPost    int64          `json:"to_post"`
	ReplyType string         `json:"reply_type"`
	Context   sql.NullString `json:"context"`
	CreatedAt time.Time      `json:"created_at"`
}

type Thread struct {
	ID          int64          `json:"id"`
	ThreadID    string         `json:"thread_id"`
	Board       string         `json:"board"`
	Subject     sql.NullString `json:"subject"`
	Source      string         `json:"source"`
	SourceUrl   sql.NullString `json:"source_url"`
	CreatedAt   time.Time      `json:"created_at"`
	LastUpdated time.Time      `json:"last_updated"`
	PostsCount  sql.NullInt64  `json:"posts_count"`
	MediaCount  sql.NullInt64  `json:"media_count"`
	Status      sql.NullString `json:"status"`
}

type User struct {
	ID              int64           `json:"id"`
	Board           string          `json:"board"`
	UserID          string          `json:"user_id"`
	Name            string          `json:"name"`
	Tripcode        sql.NullString  `json:"tripcode"`
	Country         sql.NullString  `json:"country"`
	CountryName     sql.NullString  `json:"country_name"`
	Flag            sql.NullString  `json:"flag"`
	FlagName        sql.NullString  `json:"flag_name"`
	FirstSeen       time.Time       `json:"first_seen"`
	LastSeen        time.Time       `json:"last_seen"`
	PostCount       sql.NullInt64   `json:"post_count"`
	TotalMediaPosts sql.NullInt64   `json:"total_media_posts"`
	AvgPostLength   sql.NullFloat64 `json:"avg_post_length"`
	MostCommonBoard sql.NullString  `json:"most_common_board"`
}
