// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	CountMediaByThread(ctx context.Context, arg CountMediaByThreadParams) (int64, error)
	CountPostsByThread(ctx context.Context, arg CountPostsByThreadParams) (int64, error)
	CountQuotesByThread(ctx context.Context, arg CountQuotesByThreadParams) (int64, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateQuote(ctx context.Context, arg CreateQuoteParams) (Quote, error)
	CreateReply(ctx context.Context, arg CreateReplyParams) error
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveUsers(ctx context.Context, arg GetActiveUsersParams) ([]GetActiveUsersRow, error)
	GetConversationTree(ctx context.Context, arg GetConversationTreeParams) ([]GetConversationTreeRow, error)
	GetDownloadedMedia(ctx context.Context, arg GetDownloadedMediaParams) ([]Medium, error)
	GetFailedDownloads(ctx context.Context, board string) ([]Medium, error)
	GetGreentextByThread(ctx context.Context, arg GetGreentextByThreadParams) ([]GetGreentextByThreadRow, error)
	GetMedia(ctx context.Context, arg GetMediaParams) (Medium, error)
	GetMediaByPost(ctx context.Context, arg GetMediaByPostParams) ([]Medium, error)
	GetMediaByThread(ctx context.Context, arg GetMediaByThreadParams) ([]Medium, error)
	GetMostRepliedPosts(ctx context.Context, arg GetMostRepliedPostsParams) ([]GetMostRepliedPostsRow, error)
	GetOriginalPost(ctx context.Context, arg GetOriginalPostParams) (Post, error)
	GetPost(ctx context.Context, arg GetPostParams) (Post, error)
	GetPostsByThread(ctx context.Context, arg GetPostsByThreadParams) ([]Post, error)
	GetPostsByUser(ctx context.Context, arg GetPostsByUserParams) ([]Post, error)
	GetQuotesByPost(ctx context.Context, arg GetQuotesByPostParams) ([]Quote, error)
	GetQuotesByThread(ctx context.Context, arg GetQuotesByThreadParams) ([]Quote, error)
	GetRecentPosts(ctx context.Context, arg GetRecentPostsParams) ([]Post, error)
	GetRepliesFrom(ctx context.Context, arg GetRepliesFromParams) ([]GetRepliesFromRow, error)
	GetRepliesTo(ctx context.Context, arg GetRepliesToParams) ([]GetRepliesToRow, error)
	GetThread(ctx context.Context, arg GetThreadParams) (Thread, error)
	GetThreadStats(ctx context.Context, board string) (GetThreadStatsRow, error)
	GetTopUsers(ctx context.Context, arg GetTopUsersParams) ([]User, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetUserConversations(ctx context.Context, arg GetUserConversationsParams) ([]GetUserConversationsRow, error)
	GetUsersByCountry(ctx context.Context, arg GetUsersByCountryParams) ([]User, error)
	ListThreads(ctx context.Context, board string) ([]Thread, error)
	ReplyExists(ctx context.Context, arg ReplyExistsParams) (int64, error)
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]Post, error)
	SearchQuotes(ctx context.Context, arg SearchQuotesParams) ([]SearchQuotesRow, error)
	UpdateMediaStatus(ctx context.Context, arg UpdateMediaStatusParams) error
	UpdateThread(ctx context.Context, arg UpdateThreadParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) error
}

var _ Querier = (*Queries)(nil)
